### ISSUE TITLE
Failed to lookup view "error" in views directory (Missing favicon)

### ISSUE THREAD

**Issue by Izhaki** [tngan/ts-express-angular2-node-boilerplate#1]
Having just tried it out, when you first open `localhost:3000` you get this error on terminal:

```
Error: Failed to lookup view "error" in views directory "/Volumes/Data/Cloud/CloudStation/Development/guitar/server/views"
    at EventEmitter.render (/Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/response.js:960:7)
    at /Volumes/Data/Cloud/CloudStation/Development/guitar/server/app.js:53:9
    at Layer.handle_error (/Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/router/index.js:310:13)
    at /Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/router/index.js:330:12)
    at IncomingMessage.next (/Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/router/index.js:271:10)
    at done (/Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/response.js:955:25)
    at EventEmitter.render (/Volumes/Data/Cloud/CloudStation/Development/guitar/node_modules/express/lib/application.js:581:14)
```

This was caused by a missing `favicon.ico` in the `public` directory.

Although I don't seem to find any `server/views` folder?

**Comment by tngan** [comment]
@Izhaki thanks, checkout the latest commit and see if it works for you.

**Comment by Izhaki** [comment]
Thanks for this. What about `server/views` not being there? Shouldn't it throw that error whenever there is a request error?

**Comment by Izhaki** [comment]
Just to verify: the fix works.
